plugins {
    id 'org.jetbrains.kotlin.plugin.serialization' version '1.8.22'
}

apply plugin: 'com.android.application'
apply plugin: 'com.jaredsburrows.license'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'

android {
    def getGitHash = { ->
        def stdout = new ByteArrayOutputStream()
        exec {
            commandLine 'git', 'rev-parse', '--short', 'HEAD'
            standardOutput = stdout
        }
        return stdout.toString().trim()
    }

    // Try reading secrets from file
    def secretsPropertiesFile = rootProject.file("secrets.properties")
    def secretProperties = new Properties()

    if (secretsPropertiesFile.exists()) {
        secretProperties.load(new FileInputStream(secretsPropertiesFile))
    }
    // Otherwise read from environment variables, this happens in CI
    else {
        secretProperties.setProperty("signing_keystore_location", "${System.getenv('signing_keystore_location')}")
        secretProperties.setProperty("signing_keystore_password", "${System.getenv('signing_keystore_password')}")
        secretProperties.setProperty("signing_key_alias", "${System.getenv('signing_key_alias')}")
        secretProperties.setProperty("signing_key_password", "${System.getenv('signing_key_password')}")
    }


    compileSdk 33
    defaultConfig {
        applicationId "cz.vitskalicky.lepsirozvrh"
        minSdkVersion 21
        targetSdkVersion 33
        versionCode 35
        versionName "1.8.7"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        buildConfigField "String", "GitHash", "\"${getGitHash()}\""
        /**
         * Whether to allow automatic crash reporting using Sentry (managed by Vít Skalický).
         * Allow only for official release builds.
         */
        buildConfigField "Boolean", "ALLOW_SENTRY", "false"
        multiDexEnabled true
        //changes apk name
        applicationVariants.configureEach { variant ->
            variant.outputs.configureEach {
                outputFileName = "Lepší rozvrh v${versionName.replace('.','-')}.apk"
            }
        }
        kapt {
            arguments {
                arg("room.schemaLocation", "$projectDir/schemas")
            }
        }
        vectorDrawables {
            useSupportLibrary true
        }
    }
    signingConfigs {
        release {
            storeFile file(secretProperties.getProperty("signing_keystore_location"))
            storePassword secretProperties.getProperty("signing_keystore_password")
            keyAlias secretProperties.getProperty("signing_key_alias")
            keyPassword secretProperties.getProperty("signing_key_password")
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        debug {
            debuggable true
            buildConfigField "Boolean", "ALLOW_SENTRY", "false"
            versionNameSuffix ".debug_${getGitHash()}"
        }
    }
    flavorDimensions "version"
    productFlavors {
        /**
         * Use this flavour.
        */
        development {
            dimension "version"
        }
        /**
         * For official releases only (f-droid and github/gitlab). Allows crash reports using Sentry, which is managed by Vít Skalický.
         * Crashes from your testing are not welcome there.
         */
        official {
            dimension "version"
            buildConfigField "Boolean", "ALLOW_SENTRY", "true"
        }
        /**
         *  For Google play releases containing google in-app purchases only.
         *  Allows crash reports using Sentry, which is managed by Vít Skalický.
         *  Crashes from your testing are not welcome there.
         */
        play {
            dimension "version"
            buildConfigField "Boolean", "ALLOW_SENTRY", "true"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
    }
    namespace 'cz.vitskalicky.lepsirozvrh'
    buildFeatures {
        compose true
    }

    composeOptions {
        kotlinCompilerExtensionVersion = "1.4.7"
    }
    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
}

licenseReport {
    generateHtmlReport = true
    generateJsonReport = false

    // These options are ignored for Java projects
    copyHtmlReportToAssets = true
    copyJsonReportToAssets = false
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.android.support:multidex:1.0.3'
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4'
    implementation 'androidx.fragment:fragment-ktx:1.6.0'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.6.1'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.1'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.3.1'
    implementation "androidx.compose.ui:ui:$compose_ui_version"
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.5.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    implementation 'joda-time:joda-time:2.11.1'
    implementation 'androidx.preference:preference-ktx:1.2.0'
    implementation 'android.arch.lifecycle:extensions:1.1.1'
    implementation 'io.sentry:sentry-android:6.4.0'
    implementation 'org.slf4j:slf4j-nop:2.0.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.13.4.2'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-joda:2.13.4'
    implementation 'com.fasterxml.jackson.module:jackson-module-kotlin:2.13.4'
    implementation 'com.jaredrummler:cyanea:1.0.2'
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-jackson:2.9.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:5.0.0-alpha.2'
    implementation "androidx.paging:paging-runtime-ktx:3.1.1"
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.1"
    androidTestImplementation "androidx.compose.ui:ui-test-junit4:$compose_ui_version"
    debugImplementation "androidx.compose.ui:ui-test-manifest:$compose_ui_version"

    def room_version = "2.5.1"

    implementation "androidx.room:room-runtime:$room_version"
    kapt "androidx.room:room-compiler:$room_version"
    implementation "androidx.room:room-ktx:$room_version"

    // Compose
    // =======

    def composeBom = platform('androidx.compose:compose-bom:2023.05.01')
    implementation composeBom
    androidTestImplementation composeBom

    // Choose one of the following:
    // Material Design 3
//    implementation 'androidx.compose.material3:material3'
    // or Material Design 2
    implementation 'androidx.compose.material:material'
    // or skip Material Design and build directly on top of foundational components
//    implementation 'androidx.compose.foundation:foundation'
    // or only import the main APIs for the underlying toolkit systems,
    // such as input and measurement/layout
//    implementation 'androidx.compose.ui:ui'

    // Android Studio Preview support
    implementation 'androidx.compose.ui:ui-tooling-preview'
    debugImplementation 'androidx.compose.ui:ui-tooling'

    // UI Tests
//    androidTestImplementation 'androidx.compose.ui:ui-test-junit4'
//    debugImplementation 'androidx.compose.ui:ui-test-manifest'

    // Optional - Included automatically by material, only add when you need
    // the icons but not the material library (e.g. when using Material3 or a
    // custom design system based on Foundation)
//    implementation 'androidx.compose.material:material-icons-core'
    // Optional - Add full set of material icons
//    implementation 'androidx.compose.material:material-icons-extended'
    // Optional - Add window size utils
//    implementation 'androidx.compose.material3:material3-window-size-class'

    // Optional - Integration with activities
    implementation 'androidx.activity:activity-compose:1.6.1'
    // Optional - Integration with ViewModels
    implementation 'androidx.lifecycle:lifecycle-viewmodel-compose:2.5.1'
    // Optional - Integration with LiveData
    implementation 'androidx.compose.runtime:runtime-livedata'
    // Optional - Integration with RxJava
//    implementation 'androidx.compose.runtime:runtime-rxjava2'


    playImplementation 'com.android.billingclient:billing:6.0.0'


}
