package cz.vitskalicky.lepsirozvrh.theme

import androidx.compose.ui.graphics.Color
import cz.vitskalicky.lepsirozvrh.BuildConfig

object DefaultRozvrhThemes {
    // Gruvbox Light
    final val LIGHT = RozvrhTheme(
        isLight = true,
        cABg = Color(0xFFebdbb2),           // gruvbox bg1
        cAPrimaryText = Color(0xFF3c3836),   // gruvbox fg
        cARoomText = Color(0xFF665c54),      // gruvbox fg2
        cASecondaryText = Color(0xFF3c3836),
        cChngBg = Color(0xFFebdbb2),
        cChngPrimaryText = Color(0xFF3c3836),
        cChngRoomText = Color(0xFF665c54),
        cChngSecondaryText = Color(0xFF3c3836),
        cDivider = Color(0xFFa89984),        // gruvbox bg4 - was bg2, which is the empty-cell
                                             // colour itself, so the grid vanished between cells
        cEmptyBg = Color(0xFFd5c4a1),
        cError = Color(0xFF9d0006),          // gruvbox red dark
        cHBg = Color(0xFFfbf1c7),            // gruvbox bg
        cHPrimaryText = Color(0xFF3c3836),
        cHRoomText = Color(0xFF665c54),
        cHSecondaryText = Color(0xFF3c3836),
        cHeaderBg = Color(0xFFd5c4a1),       // gruvbox bg2
        cHeaderPrimaryText = Color(0xFF3c3836),
        cHeaderSecondaryText = Color(0xFF504945), // gruvbox fg1
        cHighlight = Color(0xFFaf3a03),      // gruvbox orange dark
        cHomework = Color(0xFF9d0006),       // gruvbox red dark
        cInfolineBg = Color(0xFF3c3836),     // gruvbox fg (dark bar)
        cInfolineText = Color(0xFFfbf1c7),   // gruvbox bg
        cPrimary = Color(0xFFaf3a03),        // gruvbox orange dark
        cSecondary = Color(0xFF076678),      // gruvbox blue dark
        cSurface = Color(0xFFfbf1c7),        // gruvbox bg
        dpDividerWidth = 1.5f,
        dpHighlightWidth = 1.0f,
        dpHomework = 5.0f,
        dpPaddingBottom = 3.0f,
        dpPaddingLeft = 3.0f,
        dpPaddingRight = 3.0f,
        dpPaddingTop = 3.0f,
        dpTextPadding = 2.0f,
        spInfolineTextSize = 12.0f,
        spPrimaryText = 18.0f,
        spSecondaryText = 12.0f,
        customizationLevel = 0,
    )

    // Gruvbox Dark
    final val DARK = RozvrhTheme(
        isLight = false,
        cABg = Color(0xFF504945),            // gruvbox bg2
        cAPrimaryText = Color(0xFFebdbb2),   // gruvbox fg
        cARoomText = Color(0xFFa89984),      // gruvbox fg4
        cASecondaryText = Color(0xFFd5c4a1), // gruvbox fg1
        cChngBg = Color(0xFF504945),
        cChngPrimaryText = Color(0xFFebdbb2),
        cChngRoomText = Color(0xFFa89984),
        cChngSecondaryText = Color(0xFFd5c4a1),
        cDivider = Color(0xFF665c54),        // gruvbox bg3 - a light-on-dark grid reads
                                             // where the old near-black one did not
        cEmptyBg = Color(0xFF1d2021),
        cError = Color(0xFFfb4934),          // gruvbox red bright
        cHBg = Color(0xFF3c3836),            // gruvbox bg1
        cHPrimaryText = Color(0xFFebdbb2),
        cHRoomText = Color(0xFFa89984),
        cHSecondaryText = Color(0xFFd5c4a1),
        cHeaderBg = Color(0xFF32302f),       // gruvbox bg soft
        cHeaderPrimaryText = Color(0xFFebdbb2),
        cHeaderSecondaryText = Color(0xFFa89984),
        cHighlight = Color(0xFFfe8019),      // gruvbox orange bright
        cHomework = Color(0xFFfabd2f),       // gruvbox yellow bright
        cInfolineBg = Color(0xFF1d2021),     // gruvbox bg hard
        cInfolineText = Color(0xFFebdbb2),
        cPrimary = Color(0xFFfe8019),        // gruvbox orange bright
        cSecondary = Color(0xFF83a598),      // gruvbox blue bright
        cSurface = Color(0xFF282828),        // gruvbox bg
        dpDividerWidth = 1.5f,
        dpHighlightWidth = 1.0f,
        dpHomework = 5.0f,
        dpPaddingBottom = 3.0f,
        dpPaddingLeft = 3.0f,
        dpPaddingRight = 3.0f,
        dpPaddingTop = 3.0f,
        dpTextPadding = 2.0f,
        spInfolineTextSize = 12.0f,
        spPrimaryText = 18.0f,
        spSecondaryText = 12.0f,
        customizationLevel = 0,
    )
    final val BLACK = RozvrhTheme(
        isLight = false,
        cABg = Color(0xFF464C4F),
        cAPrimaryText = Color(0xFFFFFFFF),
        cARoomText = Color(0xFFE3E8EB),
        cASecondaryText = Color(0xFFFFFFFF),
        cChngBg = Color(0xFF464C4F),
        cChngPrimaryText = Color(0xFFFFFFFF),
        cChngRoomText = Color(0xFFE3E8EB),
        cChngSecondaryText = Color(0xFFFFFFFF),
        cDivider = Color(0xFF121212),
        cEmptyBg = Color(0xFF121212),
        cError = Color(0xFFCF6679),
        cHBg = Color(0xFF000000),
        cHPrimaryText = Color(0xFFFFFFFF),
        cHRoomText = Color(0xFFE3E8EB),
        cHSecondaryText = Color(0xFFFFFFFF),
        cHeaderBg = Color(0xFF242424),
        cHeaderPrimaryText = Color(0xFFFFFFFF),
        cHeaderSecondaryText = Color(0xFFFFFFFF),
        cHighlight = Color(0xFFF9A825),
        cHomework = Color(0xFFF9A825),
        cInfolineBg = Color(0xFF424242),
        cInfolineText = Color(0xFFFFFFFF),
        cPrimary = Color(0xFFF9A825),
        cSecondary = Color(0xFFCFD8DC),
        cSurface = Color(0xFF000000),
        dpDividerWidth = 1.5f,
        dpHighlightWidth = 1.0f,
        dpHomework = 5.0f,
        dpPaddingBottom = 3.0f,
        dpPaddingLeft = 3.0f,
        dpPaddingRight = 3.0f,
        dpPaddingTop = 3.0f,
        dpTextPadding = 2.0f,
        spInfolineTextSize = 12.0f,
        spPrimaryText = 18.0f,
        spSecondaryText = 12.0f,
        customizationLevel = 0,
    )

    // as visible as possible if debug, hope it is unnoticed in production
    // Nord
    final val NORD = RozvrhTheme(
        isLight = false,
        cABg = Color(0xFF434c5e),
        cAPrimaryText = Color(0xFFeceff4),
        cARoomText = Color(0xFFd8dee9),
        cASecondaryText = Color(0xFFe5e9f0),
        cChngBg = Color(0xFF434c5e),
        cChngPrimaryText = Color(0xFFeceff4),
        cChngRoomText = Color(0xFFd8dee9),
        cChngSecondaryText = Color(0xFFe5e9f0),
        cDivider = Color(0xFF4c566a),
        cEmptyBg = Color(0xFF2e3440),
        cError = Color(0xFFbf616a),
        cHBg = Color(0xFF3b4252),
        cHPrimaryText = Color(0xFFeceff4),
        cHRoomText = Color(0xFFd8dee9),
        cHSecondaryText = Color(0xFFe5e9f0),
        cHeaderBg = Color(0xFF2e3440),
        cHeaderPrimaryText = Color(0xFFeceff4),
        cHeaderSecondaryText = Color(0xFFd8dee9),
        cHighlight = Color(0xFF88c0d0),
        cHomework = Color(0xFFbf616a),
        cInfolineBg = Color(0xFF2e3440),
        cInfolineText = Color(0xFFd8dee9),
        cPrimary = Color(0xFF88c0d0),
        cSecondary = Color(0xFFa3be8c),
        cSurface = Color(0xFF3b4252),
        dpDividerWidth = 1.0f,
        dpHighlightWidth = 1.0f,
        dpHomework = 5.0f,
        dpPaddingBottom = 3.0f,
        dpPaddingLeft = 3.0f,
        dpPaddingRight = 3.0f,
        dpPaddingTop = 3.0f,
        dpTextPadding = 2.0f,
        spInfolineTextSize = 12.0f,
        spPrimaryText = 18.0f,
        spSecondaryText = 12.0f,
        customizationLevel = 0,
    )

    // Solarized Light
    final val SOLARIZED = RozvrhTheme(
        isLight = true,
        cABg = Color(0xFFeee8d5),
        cAPrimaryText = Color(0xFF657b83),
        cARoomText = Color(0xFF93a1a1),
        cASecondaryText = Color(0xFF586e75),
        cChngBg = Color(0xFFeee8d5),
        cChngPrimaryText = Color(0xFF657b83),
        cChngRoomText = Color(0xFF93a1a1),
        cChngSecondaryText = Color(0xFF586e75),
        cDivider = Color(0xFFd9d2be),
        cEmptyBg = Color(0xFFe0dac6),
        cError = Color(0xFFdc322f),
        cHBg = Color(0xFFfdf6e3),
        cHPrimaryText = Color(0xFF657b83),
        cHRoomText = Color(0xFF93a1a1),
        cHSecondaryText = Color(0xFF586e75),
        cHeaderBg = Color(0xFFe0dac6),
        cHeaderPrimaryText = Color(0xFF586e75),
        cHeaderSecondaryText = Color(0xFF657b83),
        cHighlight = Color(0xFFcb4b16),
        cHomework = Color(0xFFdc322f),
        cInfolineBg = Color(0xFF073642),
        cInfolineText = Color(0xFFeee8d5),
        cPrimary = Color(0xFF268bd2),
        cSecondary = Color(0xFF2aa198),
        cSurface = Color(0xFFfdf6e3),
        dpDividerWidth = 1.0f,
        dpHighlightWidth = 1.0f,
        dpHomework = 5.0f,
        dpPaddingBottom = 3.0f,
        dpPaddingLeft = 3.0f,
        dpPaddingRight = 3.0f,
        dpPaddingTop = 3.0f,
        dpTextPadding = 2.0f,
        spInfolineTextSize = 12.0f,
        spPrimaryText = 18.0f,
        spSecondaryText = 12.0f,
        customizationLevel = 0,
    )

    // Dracula
    final val DRACULA = RozvrhTheme(
        isLight = false,
        cABg = Color(0xFF44475a),
        cAPrimaryText = Color(0xFFf8f8f2),
        cARoomText = Color(0xFFbd93f9),
        cASecondaryText = Color(0xFFf8f8f2),
        cChngBg = Color(0xFF44475a),
        cChngPrimaryText = Color(0xFFf8f8f2),
        cChngRoomText = Color(0xFFbd93f9),
        cChngSecondaryText = Color(0xFFf8f8f2),
        cDivider = Color(0xFF44475a),
        cEmptyBg = Color(0xFF1e2029),
        cError = Color(0xFFff5555),
        cHBg = Color(0xFF282a36),
        cHPrimaryText = Color(0xFFf8f8f2),
        cHRoomText = Color(0xFF8be9fd),
        cHSecondaryText = Color(0xFFf8f8f2),
        cHeaderBg = Color(0xFF1e2029),
        cHeaderPrimaryText = Color(0xFFf8f8f2),
        cHeaderSecondaryText = Color(0xFFbd93f9),
        cHighlight = Color(0xFFff79c6),
        cHomework = Color(0xFFff5555),
        cInfolineBg = Color(0xFF1e2029),
        cInfolineText = Color(0xFFf8f8f2),
        cPrimary = Color(0xFFbd93f9),
        cSecondary = Color(0xFF50fa7b),
        cSurface = Color(0xFF282a36),
        dpDividerWidth = 1.0f,
        dpHighlightWidth = 1.0f,
        dpHomework = 5.0f,
        dpPaddingBottom = 3.0f,
        dpPaddingLeft = 3.0f,
        dpPaddingRight = 3.0f,
        dpPaddingTop = 3.0f,
        dpTextPadding = 2.0f,
        spInfolineTextSize = 12.0f,
        spPrimaryText = 18.0f,
        spSecondaryText = 12.0f,
        customizationLevel = 0,
    )

    final val UNSPECIFIED = if (BuildConfig.DEBUG)
        RozvrhTheme(
            isLight = false,
            cABg = Color.Magenta,
            cAPrimaryText = Color.Cyan,
            cARoomText = Color.Cyan,
            cASecondaryText = Color.Cyan,
            cChngBg = Color.Magenta,
            cChngPrimaryText = Color.Cyan,
            cChngRoomText = Color.Cyan,
            cChngSecondaryText = Color.Cyan,
            cDivider = Color.Magenta,
            cEmptyBg = Color.Magenta,
            cError = Color.Magenta,
            cHBg = Color.Magenta,
            cHPrimaryText = Color.Cyan,
            cHRoomText = Color.Cyan,
            cHSecondaryText = Color.Cyan,
            cHeaderBg = Color.Magenta,
            cHeaderPrimaryText = Color.Cyan,
            cHeaderSecondaryText = Color.Cyan,
            cHighlight = Color.Magenta,
            cHomework = Color.Magenta,
            cInfolineBg = Color.Magenta,
            cInfolineText = Color.Cyan,
            cPrimary = Color.Magenta,
            cSecondary = Color.Magenta,
            cSurface = Color.Magenta,
            dpDividerWidth = 1.0f,
            dpHighlightWidth = 1.0f,
            dpHomework = 5.0f,
            dpPaddingBottom = 3.0f,
            dpPaddingLeft = 3.0f,
            dpPaddingRight = 3.0f,
            dpPaddingTop = 3.0f,
            dpTextPadding = 2.0f,
            spInfolineTextSize = 12.0f,
            spPrimaryText = 18.0f,
            spSecondaryText = 12.0f,
            customizationLevel = 0,
        ) else LIGHT
}
